# Welcome to Jekyll!
#
# This config file is meant for settings that affect the whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#

## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: tomorrow-night-bright # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url: https://www.alainqtec.com # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: "" # does not include hostname
title: alainQtec
description: > # this means to ignore newlines until "Language & timezone"
  Howdy ! I'm Alain, a developer ðŸ‘¨â€ðŸ’». passionate and helping you get more done, using quick tech solutions.
homeurl: "/"
blogurl: "/blog"
shopurl: "/shop"
abouturl: "/about"
galleryurl: "/gallery"
contacturl: "/contact"
privacyurl: "/privacy-policy"
termsurl: "/terms-of-service"
## => Language and Timezone
##############################
lang: en # the language of your site, default as "en"
timezone: Africa/Kigali # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: alainQtec/tech-blog
repository_tree: main

## => Paths
##############################
paths:
  root: # title link url, "/" (default)
  home: # home layout url, "/" (default)
  blog: "/blog"
  shop: "/shop"
  about: "/about"
  gallery: "/gallery"
  contact: "/contact"
  archive: # "/archive.html" (default)
  rss: # "/feed.xml" (default)
  privacy: "/privacy-policy"
  terms: "/terms-of-service"

urls:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog
    url: /blog
  - text: Gallery
    url: /gallery
  - text: Shop
    url: /shop
  - text: Contact
    url: /contact

## => Author and Social
##############################

author_logo: profile.png
author: Alain Herve
author_bio: Passionate developer, helping you get more done, using quick tech solutions.
author_email: "alainhervem@gmail.com"
author_location: Earth
author_website_url: "https://alainqtec.com"
typewrite-text: Thanks for visiting.

# author:
#   type: # "person" (default), "organization"
#   name: Alain Herve
#   url: https://alainqtec.com
#   avatar: # path or url of avatar image (square)
#   bio: Passionate developer, helping you get more done, using quick tech solutions.
#   email: "alainhervem@gmail.com"
#   facebook: "alainQtec" # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
#   twitter: "alainQtec" # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
#   weibo: # "alainQtec" # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
#   googleplus: "alainQtec" # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
#   telegram: "alainQtec" # "user_name" the last part of your profile url, e.g. https://t.me/user_name
#   medium: "alainQtec" # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
#   zhihu: # "alainQtec" # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
#   douban: # "alainQtec" # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
#   linkedin: "alainQtec" # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
#   github: "alainQtec" # "user_name" the last part of your profile url, e.g. https://github.com/user_name
#   npm: "alainQtec" # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name

author_work_experiences:
  - company_name: Google
    company_logo: google.png
    company_url: https://google.com
    designation: Software Engineer
    description: Worked on various Google Products
    visibility: true

  - company_name: Microsoft
    company_logo: microsoft.png
    company_url: https://microsoft.com
    designation: Azure Developer
    description: Worked on various Azure Cloud Products
    visibility: true

author_education_details:
  - college_logo: project.png
    college_name: MIT
    college_url: https://mit.org
    college_degree: CS Engineer
    description: Bachelor of Technology
    visibility: true

author_project_details:
  - project_thumbnail: project.png
    project_title: $appname
    project_description: A windows 11/10 utility app to easily troubleshoot and optimize the system for end-users.
    project_url: https://alainqtec.com/apps/$appname
    visibility: true
  - project_thumbnail: dashb_chart.jpg
    project_title: Admin Toolpack
    project_description: A small windows app built for network and system admins.
    project_url: https://alainqtec.com/apps/$appname
    visibility: true

twitter_username: alainQtec
github_username: alainQtec
facebook_username: alainQtec
linkedin_username: alainQtec
behance_username: alainQtec
instagram_username: alainQtec
medium_username: alainQtec
telegram_username: alainQtec
dribbble_uszername: alainQtec
flickr_username: alainQtec

algolia:
  application_id: O83A8CEWFW
  index_name: prod_alainQtec # You can replace that with whatever name you want. I used the preffix "prod_" as in production environment
wakatime_username: alainQtec

mailchimp_form_url: https://alainqtec.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

formspree_email: alainhervem@gmail.com

# markdown: kramdown
# tomorrow-night-bright
# highlighter: rouge
# permalink: pretty

show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

jekyll_admin:
  homepage: "pages"
  hidden_links:
    - configuration
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  - scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  - scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

#     defaults:
# - scope:
#     path: ""
#     type: posts
#   values:
#     layout: article
#     sharing: true
#     license: true
#     aside:
#       toc: true
#     show_edit_on_github: true
#     show_subscribe: true
#     pageview: true

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)

## => Markdown Enhancements
##############################
## Mathjax
mathjax: true # false
mathjax_autoNumber: true # false

## Mermaid
mermaid: true # false

## Chart
chart: true # false

## => Paginate
##############################
paginate: 5
paginate_path: "/blog/page/:num/" # don't change this unless for special need . ex: paginate_path: /page:num
per_page: 5

## => Sources
##############################
sources: # bootcdn (default), unpkg

## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx

## => Comments
##############################
comments:
  provider: false # false (default), "disqus", "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID: # GitHub Application Client ID
    clientSecret: # GitHub Application Client Secret
    repository: # GitHub repo
    owner: # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
    Id: # - your GitHub Id

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id: # LeanCloud App id
    app_key: # LeanCloud App key
    placeholder: # Prompt information
    visitor: # false (default)
    meta: # "[nick, mail, link]" (default) nickname, E-mail, Personal-site

## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id: # LeanCloud App id
    app_key: # LeanCloud App key
    app_class: # LeanCloud App class

## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID

## => Analytics
##############################
analytics:
  provider: google # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id: # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics

## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: pretty # or permalink: date

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-admin
  - jekyll-menus

data_dir: /_data
